name: Deploy index.html to S3

on:
  push:
    branches:
      - main

jobs:
  deployStaticFileToS3:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # AWS CLI のセットアップ
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1 # 使用するリージョンを指定
      # # Docker と docker-compose のインストール
      # - name: Install Docker Compose
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker-compose
      # Docker Compose を使ったビルド
      - name: Build Vue.js project with Docker Compose
        run: |
          docker compose run --rm vue npm install
          docker compose run --rm vue npm run build

      # # S3 にリポジトリの最上位ディレクトリにあるindex.htmlファイルをデプロイ
      # - name: Copy index.html to S3
      #   run: |
      #     aws s3 cp ./index.html s3://h4b-roo-backet01
      # S3 にリポジトリの最上位ディレクトリからvue/ViteTestCICDProject/distの中身全部をデプロイ
      - name: Copy files at dist to S3
        run: |
          aws s3 sync ./vue/ViteTestCICDProject/dist s3://h4b-roo-backet01
